version: 2
jobs:
        test: 
                docker:
                        - image: ubuntu:18.04
                          environment:
                                  PIPENV_VENV_IN_PROJECT: true
                branches:
                        only:
                                - master

                steps:
                        - checkout
                        - run: 
                                name: setting up apt-get properly
                                command: |
                                        apt-get update -y
                        - run:
                                name: Installing dependencies
                                command: |
                                        #add-apt-repository -y ppa:ubuntu-toolchain-r/test 
                                        #apt-get install -y gcc-5 g++-5 
                                        apt-get install -y cmake
                                        apt-get install -y python3-pip
                                        apt-get install -y python3.6
                                        apt-get install -y git
                                        apt-get install -y libboost-test-dev
                                        apt-get install -y doxygen
                                        sudo apt-get remove clang
                                        sudo apt-get install clang-5.0 libclang-common-5.0-dev libllvm5.0
                        - run:
                                command: | 
                                        clang --version
                                #                        - run: 
                                #                                name: installing python packages
                                #                                command: |
                                #                                        python3.6 -m pip install --upgrade pip
                                #                                        python3.6 -m pip install numpy scipy sphinx breathe sphinx_rtd_theme
                                #                        - run: 
                                #                                command: |
                                #                                        rm -rf build 
                                #                                        mkdir build 
                                #                                        cd build 
                                #                                        cmake -DENABLE_DOC=ON -DBUILD_TESTS=ON .. 
                                #                        - run: pwd
                                #                        - run:
                                #                                command: | 
                                #                                        cd build 
                                #                                        make lint
                                #                        - run: 
                                #                                command: |
                                #                                        cd build 
                                #                                        make 
                                #                        - run: 
                                #                                command: |
                                #                                        cd build 
                                #                                        ctest -V
                                #                        - run: 
                                #                                command: |
                                #                                        cd build 
                                #                                        make dev_doc
                                #
                                #                                        
                                #
